### ISSUE TITLE
ChatGPT version 1.1.0

### ISSUE THREAD

**Issue by asheroto** [targed/chocolatey-projects#1]
Hello,

[lencx/ChatGPT](https://github.com/lencx/ChatGPT) is on version 1.1.0 released Aug 3, 2023. The [Chocolatey repository version](https://community.chocolatey.org/packages/chatgpt) is outdated having version 0.10.3 on Feb 14, 2023. Are you still planning on updating this package?

If you would like some help, I'm happy to assist with the repository, my Chocolatey username is the same as on GitHub.

Thank you

**Comment by targed** [comment]
Thank you for noticing. I have been trying to push for a while but every time I do I get the error

`An error has occurred. It's possible the package version already exists on the repository or a nuspec element is invalid. See error below...
Response status code does not indicate success: 409 (Conflict).`

I can't figure out how to fix it. If you know anything about it, I would greatly apprecate it.

**Comment by asheroto** [comment]
Hello,

Glad you're still around! 😊 I actually e-mailed you via "Contact Maintainers" on the ChatGPT package, did you not receive an e-mail through there?

It appears that the reason it's failing is because there is a lot of extra data in the package that should be removed. Things like CDATA and other comments are notes that are generally not left in most package nuspec files. 😊

I recommend using the [choco-nuspec-checker](https://community.chocolatey.org/packages/choco-nuspec-checker). You just type "cnc" in the package directory like so...

![image](https://github.com/targed/chocolatey-projects/assets/49938263/de2387ce-b119-4b52-a3c1-1925246fe4bf)

I went ahead and worked on this. You can add me as a package maintainer if you'd like, no pressure though. I manage a [handful of packages](https://community.chocolatey.org/profiles/asheroto). I've also created a PR #2 on your repo.

![image](https://github.com/targed/chocolatey-projects/assets/49938263/fea1e743-b581-4e97-a20b-d24dc4e4c475)

Now CNC works.

**Comment by targed** [comment]
So sorry, I just saw that those emails got filtered. I see them now. 

Thank you very much for helping me with this. I did not know about the cnc package, but I will be using it from now on. I added you as a maintainer for the package. 

Again, thank you so much. I will look out for emails and I hope to continue working with you in the future.

**Comment by asheroto** [comment]
Happy to help! Yeah `cnc` is great! It'll even fix some things for you with arguments (it'll tell you about them if needed).

For some reason I didn't get an email about accepting to be a maintainer on the package. What does it show on your end?

https://community.chocolatey.org/packages/chatgpt

**Comment by targed** [comment]
I would love to know about any feature that would make Chocolatey better. 

That is weird, it shows that it is pending approval https://community.chocolatey.org/packages/chatgpt/1.1.0 I will see what can be done about it in the morning.

**Comment by asheroto** [comment]
Somehow my email wasn't confirmed, so I just confirmed it. Can you try to remove me and add me again? I guess there's no way for me to accept it without receiving the email. It's weird because I receive other Chocolatey emails, but I'm guessing that's why it didn't work. 😊

Thanks!

**Comment by targed** [comment]
I will do it in the morning as it is very late here. Thank you for you help! Goodnight.

**Comment by targed** [comment]
I submitted it again, so you should have got a confirmation email.

**Comment by asheroto** [comment]
I did not receive any notification. I will reach out to the admins to see if there is a site bug with that. If you have a screenshot you could share that would help, that way I can send the admins a link to this issue for details. Thank you!

**Comment by targed** [comment]
Yeah, that is super weird. I checked, and you are in the .nuspec file as an owner. I also downloaded the .nupkg, renamed it as a zip, looked inside at the .nuspec file, and you were listed in there as well. Here are the screenshots. Feel free to contact whomever in order to resolve this. 

<img width="919" alt="Screenshot 2023-09-23 173218" src="https://github.com/targed/chocolatey-projects/assets/69736930/6fd5fe4b-200c-4244-9614-123c0ee40c50">
<img width="510" alt="Screenshot 2023-09-23 173148" src="https://github.com/targed/chocolatey-projects/assets/69736930/f8a8b01e-419e-438e-9212-c93de765dd6b">
<img width="927" alt="Screenshot 2023-09-23 172951" src="https://github.com/targed/chocolatey-projects/assets/69736930/97ce4782-b349-4298-90f6-22e9635319c0">

**Comment by asheroto** [comment]
Oh that won't do it. You have to look at the repo and click manage maintainers in the left.

**Comment by targed** [comment]
Oh, I get it. Just added you. Sorry about that.

**Comment by asheroto** [comment]
haha no you invited me to be a contributor on the GitHub repo. You have to do manage maintainers on the Chocolatey package. 😎

**Comment by targed** [comment]
Oh, oops. I'm so sorry for all of this. I'm new to this. Thank you for your patience. I think I added you. Again, sorry, I'm still figuring it out.

**Comment by asheroto** [comment]
It's okay, we're almost there, now it says the invitation may have been revoked. lol

![Screenshot_2023-09-23-18-51-14-11_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/targed/chocolatey-projects/assets/49938263/7b6a3488-1195-454a-8f79-3003748d1495)

**Comment by asheroto** [comment]
Hey we're good now! Cool thanks! Closing the issue.
